// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class SerialTrackerCommandRequestT {
  private String command;

  public String getCommand() { return command; }

  public void setCommand(String command) { this.command = command; }


  public SerialTrackerCommandRequestT() {
    this.command = null;
  }
}

